openapi: 3.0.3
info:
  title: REVIRO Internship Project API
  version: 1.0.0
  description: This projects API is designed specifically to pass through the selection
    process to get a spot in REVIRO company
paths:
  /api/companies:
    get:
      operationId: company_list
      description: Allows to `GET` a list of all companies in database, paginated
        to 10 instances per page.
      summary: Gets all companies.
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - Companies
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCompanyList'
          description: ''
    post:
      operationId: company_create
      description: Allows to `POST` a new company.
      summary: Creates new company.
      tags:
      - Companies
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Company'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Company'
        required: true
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
          description: ''
  /api/companies/{company_id}:
    get:
      operationId: company_retrieve
      description: Allows to `GET` a company from database.
      summary: Gets company.
      parameters:
      - in: path
        name: company_id
        schema:
          type: integer
        required: true
      tags:
      - Companies
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
          description: ''
    put:
      operationId: company_update
      description: Allows to `PUT` a company.
      summary: Updates company.
      parameters:
      - in: path
        name: company_id
        schema:
          type: integer
        required: true
      tags:
      - Companies
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Company'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Company'
        required: true
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
          description: ''
    patch:
      operationId: company_partial_update
      description: Allows to `PATCH` a company.
      summary: Partially updates company.
      parameters:
      - in: path
        name: company_id
        schema:
          type: integer
        required: true
      tags:
      - Companies
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCompany'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCompany'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCompany'
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
          description: ''
    delete:
      operationId: company_destroy
      description: Allows to `DELETE` a company.
      summary: Deletes company.
      parameters:
      - in: path
        name: company_id
        schema:
          type: integer
        required: true
      tags:
      - Companies
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/companies/{company_id}/products:
    get:
      operationId: companies_products_list
      description: Allows to `GET` all products related to `company_id` and paginates
        10 instances per page.
      summary: Gets all products.
      parameters:
      - in: path
        name: company_id
        schema:
          type: integer
        required: true
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - Products
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedProductList'
          description: ''
    post:
      operationId: companies_products_create
      description: Allows to `POST` a new product.
      summary: Creates new product.
      parameters:
      - in: path
        name: company_id
        schema:
          type: integer
        required: true
      tags:
      - Products
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Product'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
  /api/companies/{company_id}/products/{product_id}:
    get:
      operationId: companies_products_retrieve
      description: Allows to `GET` a product.
      summary: Gets a product.
      parameters:
      - in: path
        name: company_id
        schema:
          type: integer
        required: true
      - in: path
        name: product_id
        schema:
          type: integer
        required: true
      tags:
      - Products
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
    put:
      operationId: companies_products_update
      description: Allows to `PUT` a product.
      summary: Updates a product.
      parameters:
      - in: path
        name: company_id
        schema:
          type: integer
        required: true
      - in: path
        name: product_id
        schema:
          type: integer
        required: true
      tags:
      - Products
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Product'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
    patch:
      operationId: companies_products_partial_update
      description: Allows to `PATCH` a product.
      summary: Partially updates product.
      parameters:
      - in: path
        name: company_id
        schema:
          type: integer
        required: true
      - in: path
        name: product_id
        schema:
          type: integer
        required: true
      tags:
      - Products
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedProduct'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedProduct'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedProduct'
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
    delete:
      operationId: companies_products_destroy
      description: Allows to `DELETE` a product.
      summary: Deletes product.
      parameters:
      - in: path
        name: company_id
        schema:
          type: integer
        required: true
      - in: path
        name: product_id
        schema:
          type: integer
        required: true
      tags:
      - Products
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    Company:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 32
        description:
          type: string
          maxLength: 1000
        schedule_start:
          type: string
          format: time
          nullable: true
        schedule_end:
          type: string
          format: time
          nullable: true
        schedule_weekdays:
          allOf:
          - $ref: '#/components/schemas/ScheduleWeekdaysEnum'
          minimum: -2147483648
          maximum: 2147483647
        phone_number:
          type: string
          nullable: true
          pattern: ^\+\d{9,15}$
          maxLength: 17
        email:
          type: string
          format: email
          nullable: true
          maxLength: 254
        map_link:
          type: string
          nullable: true
          maxLength: 2000
        social_media1:
          type: string
          format: uri
          nullable: true
          maxLength: 200
        social_media2:
          type: string
          format: uri
          nullable: true
          maxLength: 200
        social_media3:
          type: string
          format: uri
          nullable: true
          maxLength: 200
      required:
      - description
      - id
      - name
    PaginatedCompanyList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Company'
    PaginatedProductList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    PatchedCompany:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 32
        description:
          type: string
          maxLength: 1000
        schedule_start:
          type: string
          format: time
          nullable: true
        schedule_end:
          type: string
          format: time
          nullable: true
        schedule_weekdays:
          allOf:
          - $ref: '#/components/schemas/ScheduleWeekdaysEnum'
          minimum: -2147483648
          maximum: 2147483647
        phone_number:
          type: string
          nullable: true
          pattern: ^\+\d{9,15}$
          maxLength: 17
        email:
          type: string
          format: email
          nullable: true
          maxLength: 254
        map_link:
          type: string
          nullable: true
          maxLength: 2000
        social_media1:
          type: string
          format: uri
          nullable: true
          maxLength: 200
        social_media2:
          type: string
          format: uri
          nullable: true
          maxLength: 200
        social_media3:
          type: string
          format: uri
          nullable: true
          maxLength: 200
    PatchedProduct:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 128
        description:
          type: string
          maxLength: 1000
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          nullable: true
        discount:
          type: integer
          maximum: 100
          minimum: 0
        quantity:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        company:
          type: integer
    Product:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 128
        description:
          type: string
          maxLength: 1000
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          nullable: true
        discount:
          type: integer
          maximum: 100
          minimum: 0
        quantity:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        company:
          type: integer
      required:
      - company
      - created_at
      - description
      - id
      - name
      - updated_at
    ScheduleWeekdaysEnum:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      type: integer
      description: |-
        * `0` - All Week Days
        * `1` - Monday
        * `2` - Tuesday
        * `3` - Wednesday
        * `4` - Thursday
        * `5` - Friday
        * `6` - Saturday
        * `7` - Sunday
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
